### PR TITLE
Android add thread files

### LINKED ISSUE #822: EOF when adding to thread on Android
**Describe the bug**
When adding a file via camera or photo library, upload works fine, but get EOF error when adding to a thread/group.

**To Reproduce**
1. Go to group or timeline view
2. Click on + to add content
3. Click on {camera} or {image} and select image/take pic
4. Select a group, add a caption if you want...
5. Click share
6. Watch as upload runs fine
7. See 'Error: Unexpected EOF' next to retry and dismiss buttons

**Expected behavior**
Should simply complete with no error.

**Screenshots**
screen shot 2019-01-11 at 11 25 49 am

**Smartphone (please complete the following information):**
 - Device: Android Nexus 5S SIM
 - OS: Android 8.1

**Additional context**
This is not an issue on iOS, so it is likely due to Android-specific code.

### PR DESCRIPTION
**Pull request by carsonfarmer**
Fixes #822.

### CODE REVIEW

File: android/app/src/main/java/com/textile/textilenode/TextileNode.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ public void addThreadFiles(final String dir, final String threadId, final String
             @Override
             public void run() {
                 try {
-                    byte[] bytes = dir.getBytes();
+                    byte[] bytes = Base64.decode(dir, Base64.DEFAULT);
```
Comment (asutula) [inline android/app/src/main/java/com/textile/textilenode/TextileNode.java]: Doh. This was surely my fault and lack of Java skillz.
