### PR TITLE
Android: avatar border radius fix

### LINKED ISSUE #837: Avatar component does not handle border-radius
At least when it's using `TextileImage`. Note, this is in the emulator.

### PR DESCRIPTION
**Pull request by sanderpick**
- Adds a `View` wrapper to `TextileImage` the includes the border radius, `overflow: hidden` is also needed
- Updates android gradle plugin to latest (3.3.0), which requires gradle 4.10.1

fixes #837

### CODE REVIEW

**Comment by sanderpick** [comment]
Seeing these DIFF bundle requests with latest gradle when doing JS reloads... definitely helps the sanity level.

screenshot 2019-01-16 06 02 43

File: App/Components/Avatar.tsx [hunk 1]
```diff
@@ -74,14 +74,16 @@ class Avatar extends React.Component<Props, State> {
...
+        <View style={{ width, height, borderRadius: this.state.borderRadius, overflow: 'hidden' }}>
+          <TextileImage
+            style={{ ...(this.props.style || {}), width, height, borderRadius: this.state.borderRadius }}
+            target={localAvatar}
+            index={0}
+            forMinWidth={widthNumber}
+            resizeMode={'cover'}
+            onLayout={this.onImageLayout}
+          />
+        </View>
```
Comment (asutula) [inline App/Components/Avatar.tsx]: Did you test if the same border radius problem exists in the other cases of this `if` statement? I'm guessing it does... When I was looking into this yesterday, the problem seemed to be that the `onLayout={this.onImageLayout}` (which results in the border radius being set) wasn't being triggered on Android. The same technique is used in those other `if` cases.

File: android/app/build.gradle [hunk 2]
```diff
@@ -124,8 +124,8 @@ android {
         applicationIdSuffix ".dev"
         minSdkVersion rootProject.ext.minSdkVersion
         targetSdkVersion rootProject.ext.targetSdkVersion
-        versionCode 0
-        versionName "0"
+        versionCode 1
```
[the remark this answers is not in the document]
Comment (asutula) [reply android/app/build.gradle]: Should be fine, it's changed by the build process. This default value is only uses when you install to and emulator or device locally.

File: App/Components/Avatar.tsx (hunk 1 above)
Comment (sanderpick) [reply App/Components/Avatar.tsx]: I didn't explicitly... but good point. Though I did see a URI based avatar and a blank Icon one (before URI resolved) from my iOS beta install, and they were both looked fine. We could wrap the whole if else block in a `View` just to be sure. Re: layout event... the border radius is coming through so it must be fired at some point. I logged it in render at one point... was zero for a couple renders, then good values.

Comment (asutula) [reply App/Components/Avatar.tsx]: Cool, yea there's a good chance that when i saw it not firing, it was just because of all the problems with AS and emulators and devices. I really can't explain how broken everything Android seemed yesterday. It was very confusing.

Comment (sanderpick) [reply App/Components/Avatar.tsx]: K, cool. You ok w/ not doing the full View wrap unless we see that issue? I pretty sure the other cases aren't an issue... probably why we hadn't seen this before all over the place.

Comment (asutula) [reply App/Components/Avatar.tsx]: yea sounds good to me
